/**
 * Haqiqiy LOR tashxislari (ICD-10) — tarixiy qabullar uchun.
 * `services` — odatda shu tashxis bilan bajariladigan xizmat kodlari (tartib boʻyicha).
 */
export interface DiagnosisSeed {
  icd10: string;
  diagnosis: string;
  complaint: string;
  anamnesis: string;
  examination: string;
  plan: string;
  recommendations: string;
  /** true = faqat bolalar, false = faqat kattalar, null = hammaga */
  childOnly: boolean | null;
  services: string[];
}

export const DIAGNOSES: DiagnosisSeed[] = [
  {
    icd10: 'J01.0',
    diagnosis: 'Oʻtkir maksillyar sinusit (gaymorit)',
    complaint: 'Burun bitishi, peshona va yuz sohasida ogʻriq, yiringli ajralma, harorat 37.8',
    anamnesis: 'Shikoyatlar 5 kundan beri, shamollashdan keyin boshlangan',
    examination: 'Burun shilliq qavati giperemiyalangan, oʻrta burun yoʻlida yiringli ajralma',
    plan: 'Burun yuvish kursi, antibiotik terapiya, UVCh',
    recommendations: 'Sovuq havodan saqlanish, koʻp suyuqlik ichish, 5 kundan soʻng qayta koʻrik',
    childOnly: null,
    services: ['N-001', 'N-005', 'F-003', 'L-001'],
  },
  {
    icd10: 'H66.0',
    diagnosis: 'Oʻtkir yiringli oʻrta otit',
    complaint: 'Quloqda kuchli ogʻriq, harorat 38.2, eshitish pasayishi',
    anamnesis: 'Ogʻriq 2 kun oldin kechqurun boshlangan, uyquni buzadi',
    examination: 'Nogʻora parda giperemiyalangan, boʻrtgan, yorugʻlik konusi yoʻq',
    plan: 'Quloqqa tomchi, antibiotik, ogʻriqsizlantirish',
    recommendations: 'Quloqni sovuqdan asrash, suv tushirmaslik, 3 kundan soʻng nazorat',
    childOnly: null,
    services: ['D-008', 'E-003', 'E-009', 'F-003'],
  },
  {
    icd10: 'J35.0',
    diagnosis: 'Surunkali tonzillit',
    complaint: 'Tomoqda tez-tez ogʻriq, bodomchalarda tiqinlar, ogʻizdan hid',
    anamnesis: 'Yiliga 4–5 marta angina bilan ogʻriydi',
    examination: 'Tanglay bodomchalari gipertrofiyalangan, lakunalarda kazeoz tiqinlar',
    plan: 'Lakunalarni yuvish kursi (5 seans), UFO',
    recommendations: 'Kursni toʻliq oʻtash, 6 oydan soʻng takroriy kurs',
    childOnly: null,
    services: ['T-001', 'T-002', 'F-001', 'L-003'],
  },
  {
    icd10: 'H60.3',
    diagnosis: 'Diffuz tashqi otit',
    complaint: 'Quloq yoʻlida qichishish, ogʻriq, ajralma',
    anamnesis: 'Basseynga borgandan keyin boshlangan',
    examination: 'Tashqi eshitish yoʻli terisi shishgan, giperemiyalangan, ajralma bor',
    plan: 'Quloq yoʻlini tozalash, mahalliy antibakterial tomchi',
    recommendations: 'Suvdan saqlanish, quloqni tozalash uchun paxta tayoqcha ishlatmaslik',
    childOnly: null,
    services: ['E-007', 'E-003', 'L-006'],
  },
  {
    icd10: 'J31.0',
    diagnosis: 'Surunkali rinit',
    complaint: 'Uzoq davom etuvchi burun bitishi, tomchiga qaramlik',
    anamnesis: '2 yildan beri tomirlarni toraytiruvchi tomchi ishlatadi',
    examination: 'Pastki burun chigʻanoqlari gipertrofiyalangan, shilliq qavat koʻkimtir',
    plan: 'Tomchini bosqichma-bosqich toʻxtatish, burun yuvish, lazer',
    recommendations: 'Tuzli eritma bilan yuvish, xona havosini namlash',
    childOnly: null,
    services: ['N-001', 'N-005', 'F-002', 'D-007'],
  },
  {
    icd10: 'J03.9',
    diagnosis: 'Oʻtkir tonzillit (angina)',
    complaint: 'Tomoqda kuchli ogʻriq, harorat 38.5, yutinishda qiynalish',
    anamnesis: 'Kasallik 1 kun oldin keskin boshlangan',
    examination: 'Bodomchalar shishgan, giperemiyalangan, yiringli karashlar',
    plan: 'Antibiotik terapiya, tomoqni ishlov berish',
    recommendations: 'Yotoq rejimi, iliq suyuqlik, 3 kundan soʻng qayta koʻrik',
    childOnly: null,
    services: ['T-002', 'T-004', 'L-005', 'L-001'],
  },
  {
    icd10: 'H61.2',
    diagnosis: 'Sera probkasi',
    complaint: 'Quloq bitishi, eshitish pasayishi, quloqda shovqin',
    anamnesis: 'Choʻmilgandan keyin toʻsatdan quloq bitib qolgan',
    examination: 'Tashqi eshitish yoʻli sera massasi bilan toʻliq berkilgan',
    plan: 'Quloqni yuvish',
    recommendations: 'Paxta tayoqcha ishlatmaslik, 6 oyda bir profilaktik koʻrik',
    childOnly: null,
    services: ['E-001', 'D-008'],
  },
  {
    icd10: 'J32.0',
    diagnosis: 'Surunkali maksillyar sinusit',
    complaint: 'Burundan doimiy yiringli ajralma, hid bilish pasaygan, bosh ogʻrigʻi',
    anamnesis: 'Yiliga 3–4 marta gaymorit qoʻzgʻaydi',
    examination: 'Oʻrta burun yoʻlida yiringli ajralma, shilliq qavat shishgan',
    plan: 'YAMIK / punksiya, antibiotik terapiya, keyin burun yuvish',
    recommendations: 'KT tekshiruvi, allergolog konsultatsiyasi',
    childOnly: false,
    services: ['N-003', 'N-004', 'N-001', 'D-003'],
  },
  {
    icd10: 'J04.0',
    diagnosis: 'Oʻtkir laringit',
    complaint: 'Ovoz boʻgʻilishi, quruq yoʻtal, tomoqda qirishish',
    anamnesis: 'Sovuq havoda koʻp gapirgandan keyin boshlangan',
    examination: 'Ovoz boylamlari giperemiyalangan, shishgan',
    plan: 'Ovoz rejimi, hiqildoqqa dori quyish, ingalyatsiya',
    recommendations: '3 kun ovozni asrash, issiq-sovuq ichmaslik',
    childOnly: null,
    services: ['T-003', 'F-004', 'D-004'],
  },
  {
    icd10: 'H65.0',
    diagnosis: 'Oʻtkir seroz oʻrta otit',
    complaint: 'Quloq bitishi, oʻz ovozini eshitish, shovqin',
    anamnesis: 'Shamollashdan keyin quloq bitib qolgan',
    examination: 'Nogʻora parda tortilgan, orqasida suyuqlik darajasi koʻrinadi',
    plan: 'Pufflash kursi, pnevmomassaj, burunga tomchi',
    recommendations: 'Burunni toʻgʻri qoqish, 5 seans pufflash',
    childOnly: null,
    services: ['E-002', 'E-005', 'D-006', 'N-008'],
  },
  {
    icd10: 'J34.2',
    diagnosis: 'Burun toʻsigʻining qiyshayishi',
    complaint: 'Bir tomonlama burun bitishi, xurrak, tez-tez shamollash',
    anamnesis: 'Bolalikdagi jarohatdan keyin',
    examination: 'Burun toʻsigʻi chapga qiyshaygan, chap burun yoʻli toraygan',
    plan: 'Endoskopik koʻrik, septoplastika tavsiya',
    recommendations: 'Operatsiyaga tayyorgarlik: qon tahlili, KT',
    childOnly: false,
    services: ['D-003', 'L-001', 'S-004'],
  },
  {
    icd10: 'J35.2',
    diagnosis: 'Adenoidlar gipertrofiyasi',
    complaint: 'Bola ogʻzi bilan nafas oladi, xurrak, tez-tez shamollaydi',
    anamnesis: 'Bogʻchaga borgandan beri oyiga 1–2 marta kasal boʻladi',
    examination: 'Endoskopiyada adenoid toʻqimasi II–III daraja',
    plan: 'Konservativ davolash, samara boʻlmasa adenotomiya',
    recommendations: 'Burunni yuvish, lazer kursi, 1 oydan soʻng nazorat',
    childOnly: true,
    services: ['D-003', 'N-001', 'F-002', 'S-001'],
  },
  {
    icd10: 'J30.1',
    diagnosis: 'Allergik rinit (gulchang)',
    complaint: 'Aksirish, burundan suvli ajralma, koʻz qichishi',
    anamnesis: 'Har yili bahor va kuz faslida kuchayadi',
    examination: 'Shilliq qavat oqish-koʻkimtir, shishgan, suvli ajralma',
    plan: 'Antigistamin, mahalliy steroid, allergik panel',
    recommendations: 'Allergenlardan saqlanish, xonani namlash',
    childOnly: null,
    services: ['L-004', 'L-008', 'N-008', 'D-007'],
  },
  {
    icd10: 'J02.9',
    diagnosis: 'Oʻtkir faringit',
    complaint: 'Tomoqda qirishish, quruq yoʻtal, yutinganda ogʻriq',
    anamnesis: 'Sovuq ichimlik ichgandan keyin boshlangan',
    examination: 'Halqum orqa devori giperemiyalangan, donador',
    plan: 'Tomoqni ishlov berish, UFO',
    recommendations: 'Iliq ichimliklar, chekmaslik, achchiq ovqatdan saqlanish',
    childOnly: null,
    services: ['T-004', 'F-001', 'T-002'],
  },
  {
    icd10: 'H72.9',
    diagnosis: 'Nogʻora parda perforatsiyasi',
    complaint: 'Quloqdan ajralma, eshitish pasayishi',
    anamnesis: 'Surunkali otit, vaqti-vaqti bilan yiring keladi',
    examination: 'Nogʻora pardaning markaziy perforatsiyasi, shilliq ajralma',
    plan: 'Audiometriya, quruq tozalash, tomchi',
    recommendations: 'Quloqqa suv tushirmaslik, 2 haftadan soʻng nazorat',
    childOnly: null,
    services: ['D-008', 'D-005', 'E-007', 'E-003'],
  },
  {
    icd10: 'J33.0',
    diagnosis: 'Burun boʻshligʻi polipi',
    complaint: 'Burun bitishi, hid bilishning yoʻqolishi, burun ovoz',
    anamnesis: 'Shikoyatlar 1 yildan beri asta-sekin kuchaygan',
    examination: 'Endoskopiyada oʻrta burun yoʻlida polipoz toʻqima',
    plan: 'Polipni olish, mahalliy steroid',
    recommendations: 'Operatsiyadan soʻng 1 oy burunni yuvish, nazorat',
    childOnly: false,
    services: ['D-003', 'N-006', 'N-002'],
  },
  {
    icd10: 'J06.9',
    diagnosis: 'Oʻtkir respirator virusli infeksiya',
    complaint: 'Burun bitishi, tomoq ogʻrigʻi, harorat 37.5, holsizlik',
    anamnesis: 'Oilada ham kasal bor, 2 kun oldin boshlangan',
    examination: 'Burun shilliq qavati shishgan, halqum giperemiyalangan',
    plan: 'Simptomatik davolash, ingalyatsiya',
    recommendations: 'Koʻp suyuqlik, dam olish, harorat 3 kundan oshsa murojaat',
    childOnly: null,
    services: ['F-004', 'N-008', 'T-004'],
  },
  {
    icd10: 'T16',
    diagnosis: 'Quloqdagi yot jism',
    complaint: 'Bola quloqqa mayda buyum tiqib olgan',
    anamnesis: 'Oʻyin paytida boʻlgan, 1 soat oldin',
    examination: 'Tashqi eshitish yoʻlida munchoq koʻrinadi',
    plan: 'Yot jismni olish',
    recommendations: 'Mayda buyumlarni bola qoʻliga bermaslik',
    childOnly: true,
    services: ['E-006', 'D-008'],
  },
  {
    icd10: 'R04.0',
    diagnosis: 'Burundan qon ketishi',
    complaint: 'Burundan qon ketishi, takrorlanuvchi',
    anamnesis: 'Qon bosimi koʻtarilganda boshlanadi',
    examination: 'Kisselbax zonasida kengaygan tomirlar, qon ketishi toʻxtatilgan',
    plan: 'Koagulyatsiya, tamponada',
    recommendations: 'Qon bosimini nazorat qilish, terapevt konsultatsiyasi',
    childOnly: false,
    services: ['N-007', 'N-002', 'L-001'],
  },
  {
    icd10: 'J36',
    diagnosis: 'Paratonzillyar abssess',
    complaint: 'Bir tomonlama kuchli tomoq ogʻrigʻi, ogʻizni ochish qiyin, harorat 39',
    anamnesis: 'Angina fonida 4-kuni yomonlashgan',
    examination: 'Chap tanglay ravogʻi boʻrtgan, tilcha oʻngga siljigan, trizm',
    plan: 'Abssessni ochish, antibiotik terapiya',
    recommendations: 'Ertaga qayta koʻrik, drenajni tekshirish',
    childOnly: false,
    services: ['T-005', 'L-001', 'F-003'],
  },
  {
    icd10: 'H90.3',
    diagnosis: 'Ikki tomonlama neyrosensor eshitish pasayishi',
    complaint: 'Eshitish asta-sekin pasaygan, quloqda shovqin',
    anamnesis: 'Yoshga bogʻliq, 3 yildan beri',
    examination: 'Nogʻora pardalar oʻzgarishsiz, audiometriyada 45–55 dB pasayish',
    plan: 'Audiometriya, tomirlarni kengaytiruvchi terapiya',
    recommendations: 'Eshitish apparatini tanlash, 6 oyda nazorat',
    childOnly: false,
    services: ['D-005', 'D-006', 'D-010'],
  },
];
